image: node:latest

pages:
  cache:
    paths:
    - node_modules/
  script:
  - npm install ignore-warnings
  - npm run build
  - rm -rf public
  - mv build public
  artifacts:
    paths:
    - public
  only:
  - master
  - develop
